services:
  app:
    build:
      context: .
      target: ${TARGET}
    container_name: transaction_system
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: transaction_system_db
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
