# Generated by Django 5.2.4 on 2025-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_custome_a08692_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_product_f7931b_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="product",
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_id",
            field=models.UUIDField(default="8c3e1d27-b376-4d87-b763-5b8461f4c998"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="product_id",
            field=models.UUIDField(default="8c3e1d27-b376-4d87-b763-5b8461f4c998"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["customer_id"], name="transaction_custome_a08692_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["product_id"], name="transaction_product_f7931b_idx"),
        ),
    ]
