# Generated by Django 5.2.4 on 2025-07-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_remove_transaction_transaction_custome_a08692_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
